version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-api3
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - mi_red_compartida

networks:
  mi_red_compartida:
    external: true
