version: '3'

services:
  db:
    container_name: notas-poli-bd
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - mi_red_compartida

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-api3
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - mi_red_compartida

networks:
  mi_red_compartida:
    external: true
